BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            text: '34'
            id: input_name
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
                on_press: app.handle_increment(1)
            Button:
                text: 'Down'
                on_press: app.handle_increment(-1)
    Button:
        text: 'Convert miles to km'
    Label:
        color: (1, 1, 0, 1)
